# Generated by Django 4.2.7 on 2023-11-19 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='days',
        ),
        migrations.RemoveField(
            model_name='group',
            name='meeting_times',
        ),
        migrations.RemoveField(
            model_name='group',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='group',
            name='meeting_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Meeting Date'),
        ),
        migrations.AddField(
            model_name='group',
            name='meeting_time',
            field=models.TimeField(default=datetime.time(12, 0), verbose_name='Meeting Time'),
        ),
        migrations.AlterField(
            model_name='group',
            name='dynamics',
            field=models.CharField(choices=[('social', 'Social'), ('intensive', 'Intensive Study'), ('mixed', 'Mixed (Study + Breaks)'), ('flexible', 'Flexible')], max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='location',
            field=models.CharField(choices=[('rutherford', 'Rutherford'), ('sperber', 'Sperber'), ('cameron', 'Cameron')], max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='session_type',
            field=models.CharField(choices=[('exam_review', 'Exam Review'), ('collab_learning', 'Collaborative Learning'), ('quiet_study', 'Quiet Study'), ('discussion_debate', 'Discussion and Debate')], max_length=100),
        ),
    ]
