# Generated by Django 4.2.7 on 2023-11-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_remove_group_days_remove_group_meeting_times_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Group Bio'),
        ),
    ]
